import colorama
print(colorama.Back.BROWN+"")
print('          ___       ___           ____             ___')
print(colorama.Back.YELLOW+"")
print('         /___\     /___\         /____\           /___\ ')
print(colorama.Back.ORANGE+"")
print('         \    \    \    \        |    |          /    /')
print(colorama.Back.RED+"")
print('          \    \    \    \       |    |         /    /')
print(colorama.Back.LIGHTBLACK_EX+"")
print('           \    \    \    \      |    |        /    /')
    print('            \    \    \    \     |    |       /    /')
    print('             \    \____\    \____|    |______/    /')
    print('             |                                   |')
    print('             |                                   |')
    print('             |                                   \___________')
    print('             \                                           @   \ ')
    print('              \                                               |=')
    print('               \                                   ______||__/')
    print('                \                                 /'
          )
    print('                 \_______________________________/')
    print('                        |             |')
    print('                       /|\           /|\ ')