import colorama

print(colorama.Fore.GREEN+"")
print(colorama.Back.LIGHTBLACK_EX+"")
input('siezer warning')

while True:
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.GREEN+"")
  print(colorama.Back.RED+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")
  print(colorama.Fore.RED+"")
  print(colorama.Back.GREEN+"")
  print("f      f")
  print("fu    uf")
  print("fun  nuf")
  print("fu    uf")
  print("f      f")
  print("f      f")