import colorama
print(colorama.Fore.GREEN+"")
print(colorama.Back.LIGHTBLACK_EX+"")
input('siezer warning')

print(colorama.Fore.GREEN+"")
print(colorama.Back.RED+"")

while True:
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.RED+"")
    print(colorama.Back.GREEN+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.GREEN+"")
    print(colorama.Back.BLUE+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.BLUE+"")
    print(colorama.Back.RED+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.RED+"")
    print(colorama.Back.GREEN+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.MAGENTA+"")
    print(colorama.Back.LIGHTBLUE_EX+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.YELLOW+"")
    print(colorama.Back.LIGHTMAGENTA_EX+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.CYAN+"")
    print(colorama.Back.LIGHTYELLOW_EX+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.BLACK+"")
    print(colorama.Back.CYAN+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTRED_EX+"")
    print(colorama.Back.RED+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTBLACK_EX+"")
    print(colorama.Back.GREEN+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTBLUE_EX+"")
    print(colorama.Back.YELLOW+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTCYAN_EX+"")
    print(colorama.Back.RED+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTGREEN_EX+"")
    print(colorama.Back.BLUE+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTBLACK_EX+"")
    print(colorama.Back.BLUE+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTMAGENTA_EX+"")
    print(colorama.Back.GREEN+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTRED_EX+"")
    print(colorama.Back.BLUE+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.LIGHTWHITE_EX+"")
    print(colorama.Back.LIGHTRED_EX+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')
    print(colorama.Fore.WHITE+"")
    print(colorama.Back.BLACK+"")
    print("hey whats up pu stahw yeh")
    print('hey whats u   u stahw yeh')
    print('hey whats       stahw yeh')
    print('hey what         tahw yeh')
    print('hey wha           ahw yeh')
    print("hey wh             hw yeh")
    print('hey w               w yeh')
    print('hey                   yeh')
    print('he                     eh')
    print('h                       h')
    print('he                     eh')
    print('hey                   yeh')
    print('hey w               w yeh')
    print('hey wh             hw yeh')
    print('hey wha           ahw yeh')
    print('hey what         tahw yeh')
    print('hey whats       stahw yeh')
    print('hey whats u   u stahw yeh')
    print('hey whats up pu stahw yeh')